#include "settings.h"
#include "../storage/ata.h"
#include <stddef.h>
#define SETTINGS_MAGIC 0x4D595354u
#define SETTINGS_VERSION 1u
#define SETTINGS_DEFAULT_LBA 8u
static uint32_t selected_lba;
static int selected_valid;
static void copy_text(char* dst,const char* src,int cap){int i=0;if(!dst||cap<=0)return;while(src&&src[i]&&i<cap-1){dst[i]=src[i];++i;}dst[i]=0;}
static uint32_t get32(const uint8_t* p){return (uint32_t)p[0]|((uint32_t)p[1]<<8)|((uint32_t)p[2]<<16)|((uint32_t)p[3]<<24);}
static void put32(uint8_t* p,uint32_t v){p[0]=(uint8_t)v;p[1]=(uint8_t)(v>>8);p[2]=(uint8_t)(v>>16);p[3]=(uint8_t)(v>>24);}
static uint16_t checksum(const uint8_t* p,int len){uint32_t sum=0;for(int i=0;i<len;++i)sum=(sum+p[i])&0xFFFFu;return (uint16_t)sum;}
static void defaults(settings_state_t* s){copy_text(s->theme,"matrix",sizeof(s->theme));copy_text(s->username,"admin",sizeof(s->username));copy_text(s->hostname,"myos",sizeof(s->hostname));s->notifications=1;s->animations=1;s->mouse_sensitivity=100;s->clock_24h=1;s->terminal_scrollback=48;}
void settings_init(void){selected_lba=SETTINGS_DEFAULT_LBA;selected_valid=ata_available()&&ata_storage_marker_present(selected_lba);}
int settings_select(uint32_t lba){if(!ata_available()||lba>=ata_sector_count())return 0;selected_lba=lba;selected_valid=ata_storage_marker_present(lba);return selected_valid;}
int settings_format(uint32_t lba){if(!ata_available()||lba>=ata_sector_count())return 0;uint8_t b[512];for(int i=0;i<512;++i)b[i]=0;put32(b,SETTINGS_MAGIC);b[4]=SETTINGS_VERSION;b[5]=1;settings_state_t s;defaults(&s);int o=8;for(int i=0;i<(int)sizeof(s.theme);++i)b[o+i]=(uint8_t)s.theme[i];o+=sizeof(s.theme);for(int i=0;i<(int)sizeof(s.username);++i)b[o+i]=(uint8_t)s.username[i];o+=sizeof(s.username);for(int i=0;i<(int)sizeof(s.hostname);++i)b[o+i]=(uint8_t)s.hostname[i];o+=sizeof(s.hostname);b[o++]=s.notifications;b[o++]=s.animations;b[o++]=s.mouse_sensitivity;b[o++]=s.clock_24h;b[o++]=(uint8_t)s.terminal_scrollback;b[o++]=(uint8_t)(s.terminal_scrollback>>8);uint16_t sum=checksum(b,o);b[6]=(uint8_t)sum;b[7]=(uint8_t)(sum>>8);if(!ata_write_sector(lba,b))return 0;selected_lba=lba;selected_valid=1;return 1;}
int settings_persistent(void){return selected_valid;}
uint32_t settings_lba(void){return selected_lba;}
int settings_load(settings_state_t* out){if(!out)return 0;defaults(out);if(!selected_valid)return 0;uint8_t b[512];if(!ata_read_sector(selected_lba,b))return 0;if(get32(b)!=SETTINGS_MAGIC||b[4]!=SETTINGS_VERSION)return 0;int o=8;for(int i=0;i<(int)sizeof(out->theme);++i)out->theme[i]=(char)b[o+i];o+=sizeof(out->theme);for(int i=0;i<(int)sizeof(out->username);++i)out->username[i]=(char)b[o+i];o+=sizeof(out->username);for(int i=0;i<(int)sizeof(out->hostname);++i)out->hostname[i]=(char)b[o+i];o+=sizeof(out->hostname);out->notifications=b[o++];out->animations=b[o++];out->mouse_sensitivity=b[o++];out->clock_24h=b[o++];out->terminal_scrollback=(uint16_t)b[o]|((uint16_t)b[o+1]<<8);o+=2;if(checksum(b,6)!=0)return 0;if(out->mouse_sensitivity<25u||out->mouse_sensitivity>200u)out->mouse_sensitivity=100;if(out->terminal_scrollback<16u||out->terminal_scrollback>512u)out->terminal_scrollback=48;out->notifications=out->notifications?1:0;out->animations=out->animations?1:0;out->clock_24h=out->clock_24h?1:0;return 1;}
int settings_save(const settings_state_t* s){if(!s||!selected_valid)return 0;uint8_t b[512];for(int i=0;i<512;++i)b[i]=0;put32(b,SETTINGS_MAGIC);b[4]=SETTINGS_VERSION;b[5]=1;int o=8;for(int i=0;i<(int)sizeof(s->theme);++i)b[o+i]=(uint8_t)s->theme[i];o+=sizeof(s->theme);for(int i=0;i<(int)sizeof(s->username);++i)b[o+i]=(uint8_t)s->username[i];o+=sizeof(s->username);for(int i=0;i<(int)sizeof(s->hostname);++i)b[o+i]=(uint8_t)s->hostname[i];o+=sizeof(s->hostname);b[o++]=s->notifications?1:0;b[o++]=s->animations?1:0;b[o++]=s->mouse_sensitivity;b[o++]=s->clock_24h?1:0;b[o++]=(uint8_t)s->terminal_scrollback;b[o++]=(uint8_t)(s->terminal_scrollback>>8);uint16_t sum=checksum(b,o);b[6]=(uint8_t)sum;b[7]=(uint8_t)(sum>>8);return ata_write_sector(selected_lba,b);}
